
public class User {
	
	// Variables
	private int ID;
	private String firstName;
	private String lastName;
	private String email;
	private String phone;
	private String username;
	private String password;
	// private boolean isLoggedIn;
	// protected boolean seatFlag; // <-- In Question.
	
	// Constructor
	public User() {
		this.ID = 0;
		this.username = "";
		this.password = "";
		//this.seatFlag = false;
		//this.isLoggedIn = false;
	}
	
	// Log In
	public void logIn() { 
		// Here we get info from GUI
		// Send to data base
	}
	
	// Sign Up
	public void signUp() { 
		// Here we get info from GUI
		// Retrieve from database
	}
	
	// Getters & Setters
	public int getID() {
		return ID;
	}
	
	// Will be a simple int for now generated by the system
	public void setID(int ID) {
		this.ID = ID;
	}

	public String getFirstName() {
		return firstName;
	}

	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}

	public String getLastName() {
		return lastName;
	}

	public void setLastName(String lastName) {
		this.lastName = lastName;
	}

	public String getEmail() {
		return email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getPhone() {
		return phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	public String getUsername() {
		return username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public String getPassword() {
		return password;
	}

	public void setPassword(String password) {
		this.password = password;
	}
	
}
